version: '3.4'

services:
  da:
    image: ghcr.io/celestiaorg/celestia-node:v0.12.3
    command: >
      celestia light start
      --p2p.network=mocha
      --keyring.accname my_celes_key
      --core.ip rpc-mocha.pops.one
      --rpc.addr=0.0.0.0
      --rpc.port=26658
      --gateway
    environment:
      - NODE_TYPE=light
      - P2P_NETWORK=mocha
    ports:
      - "26658:26658"
    volumes:
      - /mnt/disks/celestia/.celestia-light-mocha-4/:/home/celestia/.celestia-light-mocha-4/
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 12G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:26659/header/1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
